version: '3'

services:
  database:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - SECRET=zf7dmcri2n1ksb6u300cz0hdaqfqvgejdfjg8ce5
      - PG_USER=postgres
      - PG_HOST=database
      - PG_DATABSE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      - database
     
